session_name: jscore#exploretalent#com
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: vim
  panes:
    - vim
  focus: true
- window_name: git
  panes:
    - shell_command:
      - git fetch
